baseURL = 'https://astrowizici.st/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'hugo-theme-fluidity'


[menus]
  [[menus.main]]
    identifier = "home"
    pageRef = "/"
    weight = 10

  [[menus.main]]
    identifier = "post"
    pageRef = "/posts"
    weight = 20

  [[menus.main]]
    identifier = "tag"
    pageRef = "/tags"
    weight = 30

  [[menus.main]]
    identifier = "archive"
    pageRef = "/archives"
    weight = 40

  [[menus.main]]
    identifier = "about"
    pageRef = "/about"
    weight = 50

  [[menus.main]]
    identifier = "search"
    pageRef = "/search"
    weight = 60 
  

 
[module]
  [[module.mounts]]
    excludeFiles = "templates/*"
    source = 'content'
    target = 'content'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

