baseURL = 'https://astrowizici.st/'
languageCode = 'en-us'
title = 'Andy Casey'
theme = 'hugo-theme-fluidity'

summaryLength = 100
hasCJKLanguage = false

pygmentsUseClasses = true
pygmentsCodefences = true

ignoreLogs = [
  "warning-goldmark-raw-html"
]

[markup]
  defaultMarkdownHandler = "goldmark"

  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true

        [markup.goldmark.extensions.passthrough.delimiters]
          block = [
            ["$$", "$$"],
            ["\\[", "\\]"],
          ]
          inline = [
            ["\\(", "\\)"],
          ]

[menus]
  [[menus.main]]
    identifier = "home"
    pageRef = "/"
    weight = 10

  [[menus.main]]
    identifier = "post"
    pageRef = "/posts"
    weight = 20

  [[menus.main]]
    identifier = "tag"
    pageRef = "/tags"
    weight = 30

  [[menus.main]]
    identifier = "contact"
    pageRef = "/contact"
    weight = 50

  [[menus.main]]
    identifier = "search"
    pageRef = "/search"
    weight = 60



[module]
  [[module.mounts]]
    excludeFiles = "templates/*"
    source = 'content'
    target = 'content'

[caches]
  [caches.images]
    dir = ':cacheDir/images'


[build.buildStats]
enable = true

[[build.cachebusters]]
source = "assets/notwatching/hugo_stats\\.json"
target = "css"

[[build.cachebusters]]
source = "(postcss|tailwind)\\.config\\.js"
target = "css"

[module.hugoVersion]
min = "0.128.0"

[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "content"
target = "content"

[[module.mounts]]
source = "hugo_stats.json"
disableWatch = true
target = "assets/notwatching/hugo_stats.json"

[params]
description = "I fit bad models to worse data."
fullContentRSS = true
mainSections = ["posts"]

[params.pageSize]
home = 5
list = 5
archives = 20

[params.listPage]
numCategoriesToShow = 1
numTagsToShow = 3
showSummary = false

[params.social]
twitter = "astrowizicist"
github = "andycasey"
linkedin = "Your_LinkedIn_username"

[params.social.share]
disabled = false
disableByType = ["not-exist"]
platforms = [
  { name = "x" },
  { name = "linkedin" },
]

[params.social.connect]
platforms = ["github", "x", "linkedin"]

[params.articleMetadata]
position = "header"

[params.toc]
disabled = false

[params.relatedPosts]
disabled = false
disableByType = ["page"]

[params.comment]
disabled = false
disableByType = ["page"]
thirdParty = """
your comment script will be loaded here
"""

[params.search]
disabled = false
provider = "pagefind"

[params.math]
math = false
mathEngine = "mathJax"

[params.enableEmoji]
enableEmoji = true
