baseURL = 'https://astrowizici.st/'
languageCode = 'en-us'
title = 'Andy Casey'
theme = 'hugo-theme-fluidity'

summaryLength = 100
hasCJKLanguage = false
enableEmoji = true

pygmentsUseClasses = true
pygmentsCodefences = true

ignoreLogs = [
  "warning-goldmark-raw-html"
]

[markup]
  defaultMarkdownHandler = "goldmark"

  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true

        [markup.goldmark.extensions.passthrough.delimiters]
          block = [
            ["$$", "$$"],
            ["\\[", "\\]"],
          ]
          inline = [
            ["\\(", "\\)"],
          ]

[menus]
  [[menus.main]]
    identifier = "home"
    pageRef = "/"
    weight = 10

  [[menus.main]]
    identifier = "post"
    pageRef = "/posts"
    weight = 20

  [[menus.main]]
    identifier = "tag"
    pageRef = "/tags"
    weight = 30

  [[menus.main]]
    identifier = "contact"
    pageRef = "/contact"
    weight = 50

  [[menus.main]]
    identifier = "search"
    pageRef = "/search"
    weight = 60 
  

 
[module]
  [[module.mounts]]
    excludeFiles = "templates/*"
    source = 'content'
    target = 'content'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

